services:
  db:
    container_name: measurements
    image: postgres:15.3
    environment:
      - POSTGRES_USER=levantos
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=measurements
    volumes:
      - db:/data/postgres
    ports:
      - 5333:5432
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
